export const exerciseData = [
  { name: "Shoulder Butterfly Stretch", image: "/exercise/shoulder butterfly strech.jpg" },
  { name: "Chin Tuck Exercise", image: "/exercise/chin tuck exercise - Copy.png" },
  { name: "Trapezius Stretching", image: "/exercise/trapezius-stretches-progressions.jpg" },
  { name: "Chin Tuck with Shoulder Against Wall", image: "/exercise/Chin-tuck-with shoulder against wall.gif" },
  { name: "Back Extensor Exercise with Hands on Back", image: "/exercise/Back-extension-exercises.jpg" },
  { name: "Back Extensor Exercise with Hands on Head", image: "/exercise/back extension exercise with hands on head.jpg" },
  { name: "Bhujangasana", image: "/exercise/bhujangasana.jpg" },
  { name: "Bridging Exercise", image: "/exercise/bridging.jpg" },
  { name: "Bridging Cross Leg", image: "/exercise/bridging cross leg.jpg" },
  { name: "Bridging on One Leg", image: "/exercise/bridging on one leg.jpg" },
  { name: "Bridging with Holding a Ball", image: "/exercise/bridging with holding a ball.jpg" },
  { name: "Trunk Lateral Flexion", image: "/exercise/trunk lateral flexion.jpg" },
  { name: "Trunk Rotation", image: "/exercise/trunk rotation stretch.jpg" },
  { name: "Trunk Rotation Stretch", image: "/exercise/trunk rotation stretch.jpg" },
  { name: "Cross Leg Gluteal Stretching", image: "/exercise/cross leg gluteal stretch.jpg" },
  { name: "Shoulder Abduction/Adduction", image: "/exercise/shoulder butterfly strech.jpg" },
  { name: "Shoulder Extension / Flexion", image: "/exercise/shoulder flexion extension.jpg" },
  { name: "Shoulder Flexion", image: "/exercise/shoulder-flexion with bar - Copy.jpg" },
  { name: "Shoulder Rotation", image: "/images/exercises/shoulder-rotation.jpg" },
  { name: "Pectoral Stretching", image: "/exercise/pectoral stretch.jpg" },
  { name: "Pectoralis Minor Stretch", image: "/exercise/Pec-minor-stretch - Copy.png" },
  { name: "Upper Body Stretching", image: "/exercise/upper body strech with door.jpeg" },
  { name: "Upper Limb Wall Slide", image: "/exercise/upperlimb wall slide.jpg" },
  { name: "Shoulder Flexion with Bar", image: "/exercise/shoulder-flexion with bar - Copy.jpg" },
  { name: "Hip Abduction Exercise", image: "/exercise/hip abduction on wall.jpg" },
  { name: "Hip Extension with Knee Bending", image: "/exercise/hip extension with knee bending - Copy.png" },
  { name: "Hip Extensor Exercise with Knee Extended", image: "/images/exercises/hip-extensor-knee-extended.jpg" },
  { name: "Knee Bending on Prone", image: "/exercise/knee-bending on prone - Copy.jpg" },
  { name: "Knee Extension with Sitting", image: "/exercise/knee extension on sitting - Copy - Copy.jpg" },
  { name: "Knee to Chest", image: "/exercise/knee to chest stretch - Copy - Copy.jpg" },
  { name: "Plantar Fascia Release", image: "/exercise/plantar-fasciitis release.jpg" },
  { name: "Heel Raise", image: "/exercise/heel raise.jpg" },
  { name: "Heel Walking", image: "/exercise/heel walikng.jpg" },
  { name: "Piriformis Stretch", image: "/exercise/piriformis-stretch.png" },
  { name: "Single Limb Stance", image: "/exercise/single limb stance - Copy.jpg" },
  { name: "Sit to Stand", image: "/exercise/sit-to-stand-exercise.jpg" },
  { name: "SLR", image: "/exercise/slr.jpg" },
  { name: "Lunges", image: "/exercise/Lunges - Copy.jpg" },
  { name: "Squats", image: "/exercise/squat.png" },
  { name: "Stepping", image: "/exercise/stepping exercise.png" },
  { name: "Stool Stepping", image: "/exercise/stool stepping.png" },
  { name: "Toe Curling", image: "/exercise/toe curling - Copy.jpg" },
  { name: "Toe Fanning", image: "/exercise/toe fanning exercise.jpg" },
  { name: "Toe Walking", image: "/exercise/Toe-Walking.jpg" },
  { name: "Kegel’s Exercise", image: "/exercise/kegel-for exercise.jpg" },
  { name: "Bell’s Palsy Exercise", image: "/exercise/bell's palsy.png" },
  { name: "Breathing Exercise", image: "/exercise/breathing exercise.jpg" },
  { name: "Hanging", image: "/images/exercises/hanging.jpg" },
];
